# Site Configuration
site:
  title: "polarnote"
  description: "A personal blog theme for Astro."
  url: "https://polarnote.pages.dev"

# Social Links
# Configure your social media links below
# To disable a social link: set to null or remove the field entirely
# Example: twitter: null (disabled) or github: "https://github.com/username" (enabled)
social:
  github: "github_url"
  linkedin: "linkedIn_url"
  twitter: null
  email: "your_email"

# Layout Configuration
layout:
  site_width: "1100px" # max-w-7xl
  post_width: "860px" # max-w-3xl

# Content Configuration
content:
  posts_per_page: 8
