# Site Configuration
site:
  title: "polarnote"
  description: "A personal blog theme for Astro."
  url: "https://polarnote.pages.dev"

# Social Links
social:
  github: "none"
  linkedin: "none"
  twitter: "none"
  email: "none"

# Layout Configuration
layout:
  site_width: "1100px" # max-w-7xl
  post_width: "860px" # max-w-3xl

# Content Configuration
content:
  posts_per_page: 8
