baseURL = 'https://example.org/'
languageCode = 'ko-KR'
title = 'Polar Note - Example Site'
theme = 'polarnote'

[params]
  description = '혁신적인 기술과 인사이트를 공유하는 개발자 블로그'
  categories = ['개발', '데이터/ML', '디자인', '프로덕트']

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Categories'
    pageRef = '/categories'
    weight = 30

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
